# Auto-label PRs based on file changes
'component/scheduler':
  - 'scheduler/**/*'
  - '**/scheduler/**/*'

'component/kv-cache':
  - 'kv-cache/**/*'
  - '**/kv-cache/**/*'

'component/routing':
  - 'routing/**/*'
  - '**/routing/**/*'

'component/docs':
  - 'docs/**/*'
  - '*.md'
  - 'README*'

'type/task':
  - 'tests/**/*'
  - '**/*_test.go'
  - '**/*_test.py'