name: Bug Report
description: Report a bug in llm-d
title: "[BUG] "
labels: ["type/bug", "priority/medium"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Clear description of the bug
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Deploy llm-d with config X
        2. Send request Y  
        3. Observe error Z
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Expected vs Actual
      description: What should happen vs what actually happens
      placeholder: |
        Expected: Response in < 100ms
        Actual: Timeout after 30s
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Environment
      description: Deployment details
      placeholder: |
        - llm-d version: v0.1.2
        - Kubernetes: 1.28
        - Cloud: GKE/EKS/AKS
        - GPU: A100/H100/none
    validations:
      required: true
      
  - type: checkboxes
    attributes:
      label: Impact Assessment
      options:
        - label: Blocks Red Hat customer deployment
        - label: Affects performance or reliability
        - label: Security implications
        - label: Reproducible in production