name: Epic
description: Large initiative spanning multiple stories
title: "[EPIC] "
labels: ["type/epic", "priority/high"]
body:
  - type: markdown
    value: |
      Epics are reviewed monthly, not weekly. Use for initiatives spanning 4+ weeks.
      
      **Auto-Labeling**: This template will automatically apply labels based on your selections below.
      
  - type: textarea
    attributes:
      label: Epic Goal
      description: High-level capability this epic enables
      placeholder: "Enable disaggregated serving for improved resource utilization"
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Success Criteria
      description: Measurable outcomes
      placeholder: |
        - [ ] Prefill and decode run independently
        - [ ] Performance improves by 20%
        - [ ] Customer demo successful
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Stories in Epic
      description: Link related issues (create them first)
      placeholder: |
        - [ ] #XX Design architecture
        - [ ] #XX Implement prefill service
        - [ ] #XX Implement decode service
        - [ ] #XX Performance testing
        
  - type: dropdown
    attributes:
      label: Target Milestone
      description: "Target release milestone for this epic"
      options:
        - v0.2 (Hinton's Harmony)
        - v0.3 (Unicorns and Bubblegum)
        - v0.4 (TBD)
        - v0.5 (TBD)
        - v0.6 (TBD)
        - v0.7 (TBD)
        - Future
    validations:
      required: true
      
  - type: dropdown
    attributes:
      label: Epic Type
      description: "Determines if this is a core or extension epic"
      options:
        - Core Epic (affects core components)
        - Extension Epic (affects extension components)
        - Mixed Epic (affects both core and extensions)
      default: 0
    validations:
      required: true
      
  - type: checkboxes
    attributes:
      label: Red Hat Impact
      description: "Will auto-apply rh-priority label if checked"
      options:
        - label: This addresses a Red Hat customer requirement
        - label: This affects Red Hat product roadmap
        - label: Critical for OpenShift AI integration
        
  - type: checkboxes
    attributes:
      label: Demo Issue
      description: "For testing and demonstrations only"
      options:
        - label: This is a demo/fake issue for testing the workflow
        
  - type: textarea
    attributes:
      label: Red Hat Impact Details
      description: How this affects commercial product
      placeholder: "Customer requirement for enterprise deployments"